name: Windows CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true   # 拉取子模块

      - name: Set up MSVC developer environment
        uses: ilammy/msvc-dev-cmd@v1

      - name: Configure with CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build Engine
        run: cmake --build build --config Release --target Engine
